# Cloudformation / SAM Template for usersService
#
# Does not handle the creation of DB tables, however does provision the IAM permission for table access.
#
# @date 4/3/2019

AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: Borehole Tracker API

Resources:

  BoreholeTrackerAPI:
    Type: AWS::Serverless::Function
    StageName: v0
    Properties:
      Handler: bin/lambdaRunner.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: demoTable
          NODE_ENV: dev

      Policies:
      # PUT POLICIES HERE!

      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{all+}
            Method: any
        GetEventAtRoot:
          Type: Api
          Properties:
            Path: /
            Method: any
      ReservedConcurrentExecutions: 5